### ISSUE TITLE
Cannot Exit Load Menu

### ISSUE THREAD

**Issue by hord-brayden** [Sirrine-Jonathan/Afghan_Trail#3]
Run the game, pick LOAD, then try to exit the load screen without loading. It gives off an null pointer exception;
Load Game Menu

1 - Jonathan.dat
2 - Help
3 - Exit Menu
>>>
3
Exception: java.lang.NullPointerException
Cause: null
Message: null
java.lang.NullPointerException
	at byui.cit260.afghan_trail.view.GameMenuView.display(GameMenuView.java:86)
	at byui.cit260.afghan_trail.controller.GameController.startGame(GameController.java:117)
	at byui.cit260.afghan_trail.view.StartProgramView.doAction(StartProgramView.java:105)
	at byui.cit260.afghan_trail.view.StartProgramView.display(StartProgramView.java:78)
	at afghan_trail.Afghan_Trail.main(Afghan_Trail.java:52)
BUILD SUCCESSFUL (total time: 2 seconds)

**Comment by Sirrine-Jonathan** [comment]
Added null check to game that should be returned from load menu
